# Generated by Django 5.1.6 on 2025-02-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
